services:
  server:
    container_name: "server"
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - "${LOCAL_SERVER_PORT}:${SERVER_CONTAINER_PORT}"
    volumes:
      - ./backend:/app
      - nodemodulesserver:/app/node_modules
      - db:/app/src/database/sqlite
      - uploads:/app/uploads
  web:
    container_name: "web"
    env_file:
      - ./web/.env
    build:
      context: ./web
    ports:
      - "${LOCAL_WEB_INTERFACE_PORT}:${WEB_INTERFACE_CONTAINER_PORT}"
    stdin_open: true
    volumes:
      - ./web:/app
      - nodemodulesweb:/app/node_modules
volumes:
  nodemodulesserver: {}
  nodemodulesweb: {}
  db: {}
  uploads: {}